### ISSUE TITLE
crash after clear data

### ISSUE THREAD

**Issue by gism** [gism/openDevClimb#3]
2020-08-31 22:00:25.251 23514-23578/com.github.gism.opendevclimb I/AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
    Build Date                       : 09/28/19
    OpenGL ES Shader Compiler Version: EV031.27.05.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-08-31 22:00:25.251 23514-23578/com.github.gism.opendevclimb I/AdrenoGLES: Build Config                     : S L 8.0.11 AArch64
2020-08-31 22:00:25.258 23514-23578/com.github.gism.opendevclimb I/AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
2020-08-31 22:00:25.259 23514-23578/com.github.gism.opendevclimb W/AdrenoUtils: <ReadGpuID_from_sysfs:194>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2020-08-31 22:00:25.259 23514-23578/com.github.gism.opendevclimb W/AdrenoUtils: <ReadGpuID:218>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2020-08-31 22:00:25.248 23514-23514/com.github.gism.opendevclimb W/RenderThread: type=1400 audit(0.0:95689): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=32421 scontext=u:r:untrusted_app:s0:c63,c257,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0
2020-08-31 22:00:25.280 23514-23578/com.github.gism.opendevclimb W/Gralloc3: mapper 3.x is not supported
2020-08-31 22:00:25.389 23514-23574/com.github.gism.opendevclimb W/sm.opendevclim: Accessing hidden method Lcom/android/org/conscrypt/ConscryptFileDescriptorSocket;->setUseSessionTickets(Z)V (greylist,core-platform-api, reflection, allowed)
2020-08-31 22:00:25.389 23514-23574/com.github.gism.opendevclimb W/sm.opendevclim: Accessing hidden method Lcom/android/org/conscrypt/ConscryptFileDescriptorSocket;->setHostname(Ljava/lang/String;)V (greylist,core-platform-api, reflection, allowed)
2020-08-31 22:00:25.390 23514-23574/com.github.gism.opendevclimb W/sm.opendevclim: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->setAlpnProtocols([B)V (greylist,core-platform-api, reflection, allowed)
2020-08-31 22:00:25.421 23514-23568/com.github.gism.opendevclimb D/FA: Connected to remote service
2020-08-31 22:00:25.520 23514-23574/com.github.gism.opendevclimb W/sm.opendevclim: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist,core-platform-api, reflection, allowed)
2020-08-31 22:00:26.140 23514-23514/com.github.gism.opendevclimb D/AndroidRuntime: Shutting down VM
2020-08-31 22:00:26.141 23514-23514/com.github.gism.opendevclimb E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.gism.opendevclimb, PID: 23514
    java.lang.RuntimeException: Unable to instantiate service com.github.gism.gripmeter.gripMeterApplication: java.lang.ClassCastException: com.github.gism.gripmeter.gripMeterApplication cannot be cast to android.app.Service
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3977)
        at android.app.ActivityThread.access$1600(ActivityThread.java:223)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1902)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassCastException: com.github.gism.gripmeter.gripMeterApplication cannot be cast to android.app.Service
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3972)
        at android.app.ActivityThread.access$1600(ActivityThread.java:223) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1902) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7548) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-08-31 22:00:26.320 23514-23514/com.github.gism.opendevclimb I/Process: Sending signal. PID: 23514 SIG: 9

**Comment by gism** [comment]
`2020-09-07 21:04:44.776 12758-12909/com.github.gism.opendevclimb I/AdrenoGLES: QUALCOMM build                   : f2ab992, I401605978b
    Build Date                       : 09/28/19
    OpenGL ES Shader Compiler Version: EV031.27.05.01
    Local Branch                     : 
    Remote Branch                    : 
    Remote Branch                    : 
    Reconstruct Branch               : 
2020-09-07 21:04:44.776 12758-12909/com.github.gism.opendevclimb I/AdrenoGLES: Build Config                     : S L 8.0.11 AArch64
2020-09-07 21:04:44.811 12758-12909/com.github.gism.opendevclimb I/AdrenoGLES: PFP: 0x005ff112, ME: 0x005ff066
2020-09-07 21:04:44.818 12758-12909/com.github.gism.opendevclimb W/AdrenoUtils: <ReadGpuID_from_sysfs:194>: Failed to open /sys/class/kgsl/kgsl-3d0/gpu_model
2020-09-07 21:04:44.818 12758-12909/com.github.gism.opendevclimb W/AdrenoUtils: <ReadGpuID:218>: Failed to read chip ID from gpu_model. Fallback to use the GSL path
2020-09-07 21:04:44.806 12758-12758/com.github.gism.opendevclimb W/RenderThread: type=1400 audit(0.0:412886): avc: denied { search } for name="kgsl-3d0" dev="sysfs" ino=32421 scontext=u:r:untrusted_app:s0:c65,c257,c512,c768 tcontext=u:object_r:sysfs_kgsl:s0 tclass=dir permissive=0
2020-09-07 21:04:44.835 12758-12913/com.github.gism.opendevclimb I/FA: Tag Manager is not found and thus will not be used
2020-09-07 21:04:44.845 12758-12909/com.github.gism.opendevclimb W/Gralloc3: mapper 3.x is not supported
2020-09-07 21:04:44.874 12758-12907/com.github.gism.opendevclimb W/sm.opendevclim: Accessing hidden method Lcom/android/org/conscrypt/OpenSSLSocketImpl;->getAlpnSelectedProtocol()[B (greylist,core-platform-api, reflection, allowed)
2020-09-07 21:04:44.982 12758-12913/com.github.gism.opendevclimb I/chatty: uid=10321(com.github.gism.opendevclimb) Measurement Wor identical 1 line
2020-09-07 21:04:45.051 12758-12913/com.github.gism.opendevclimb D/FA: Connected to remote service
2020-09-07 21:04:45.818 12758-12758/com.github.gism.opendevclimb D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-09-07 21:04:45.820 12758-12758/com.github.gism.opendevclimb E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.gism.opendevclimb, PID: 12758
    java.lang.RuntimeException: Unable to instantiate service com.github.gism.gripmeter.gripMeterApplication: java.lang.ClassCastException: com.github.gism.gripmeter.gripMeterApplication cannot be cast to android.app.Service
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3977)
        at android.app.ActivityThread.access$1600(ActivityThread.java:223)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1902)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassCastException: com.github.gism.gripmeter.gripMeterApplication cannot be cast to android.app.Service
        at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
        at androidx.core.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:66)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3972)
        at android.app.ActivityThread.access$1600(ActivityThread.java:223) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1902) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7548) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
2020-09-07 21:04:46.042 12758-12758/com.github.gism.opendevclimb I/Process: Sending signal. PID: 12758 SIG: 9`

**Comment by gism** [comment]
Closed
Wrong casting for FCM
